# Generated by Django 6.0 on 2026-01-07 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_category_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.categorytitle'),
        ),
    ]
