# Generated by Django 6.0 on 2026-01-08 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_categorytitle_alter_category_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_title', models.CharField(max_length=50)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.year')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='make',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problems.make'),
            preserve_default=False,
        ),
    ]
