# Generated by Django 6.0 on 2026-01-09 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_make_category_make'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_title', models.CharField(max_length=100)),
                ('category_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.categorytitle')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.make')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.year')),
            ],
        ),
    ]
