# Generated by Django 6.0 on 2026-03-12 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilterTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_title', models.CharField(choices=[('recent', 'Most Recent Photos'), ('popular', 'Most Popular Photos'), ('review', 'TrueDelta Review Photos'), ('filter', 'Filter car searches by')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.filtertitle')),
            ],
        ),
    ]
