# Generated by Django 6.0 on 2026-01-16 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reliability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_title',
        ),
        migrations.AddField(
            model_name='report',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reliability.reporttitle'),
            preserve_default=False,
        ),
    ]
