# Generated by Django 6.0 on 2026-01-30 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearNumber', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.yearnumber'),
        ),
    ]
